// <auto-generated />
using System;
using AgriOpsAI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgriOpsAI.Api.Migrations
{
    [DbContext(typeof(AgriOpsDbContext))]
    [Migration("20260909132432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgriOpsAI.Api.Models.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("OptimalGrowthDurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Variety")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.CropSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TargetEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("FieldId");

                    b.ToTable("CropSeasons");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalArea")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaSize")
                        .HasColumnType("numeric");

                    b.Property<string>("BoundaryCoordinates")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Harvest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CropSeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QualityGrade")
                        .HasColumnType("text");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("YieldAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CropSeasonId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Planting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CropSeasonId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlantingMethod")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CropSeasonId");

                    b.ToTable("Plantings");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.SoilRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NitrogenLevel")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PhLevel")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhosphorusLevel")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PotassiumLevel")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("SoilRecords");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.CropSeason", b =>
                {
                    b.HasOne("AgriOpsAI.Api.Models.Crop", "Crop")
                        .WithMany("CropSeasons")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriOpsAI.Api.Models.Field", "Field")
                        .WithMany("CropSeasons")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Field", b =>
                {
                    b.HasOne("AgriOpsAI.Api.Models.Farm", "Farm")
                        .WithMany("Fields")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Harvest", b =>
                {
                    b.HasOne("AgriOpsAI.Api.Models.CropSeason", "CropSeason")
                        .WithMany("Harvests")
                        .HasForeignKey("CropSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropSeason");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Planting", b =>
                {
                    b.HasOne("AgriOpsAI.Api.Models.CropSeason", null)
                        .WithMany("Plantings")
                        .HasForeignKey("CropSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.SoilRecord", b =>
                {
                    b.HasOne("AgriOpsAI.Api.Models.Field", "Field")
                        .WithMany("SoilRecords")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Crop", b =>
                {
                    b.Navigation("CropSeasons");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.CropSeason", b =>
                {
                    b.Navigation("Harvests");

                    b.Navigation("Plantings");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Farm", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("AgriOpsAI.Api.Models.Field", b =>
                {
                    b.Navigation("CropSeasons");

                    b.Navigation("SoilRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
