import axios from 'axios';

// Base Axios instance pointing to Vite proxy or env variable
export const api = axios.create({
  baseURL: import.meta.env.VITE_API_URL || '/api',
  headers: {
    'Content-Type': 'application/json',
  },
  timeout: 10000,
});

export const aiApi = axios.create({
  baseURL: import.meta.env.VITE_AI_URL || '/ai',
  headers: {
    'Content-Type': 'application/json',
  },
  timeout: 30000,
});

// Mock Initial Fallback Data for offline demo / decoupled development
export const INITIAL_MOCK_WORKERS = [
  {
    id: 'w-101',
    name: 'Kasun Bandara',
    skills: ['PesticideCertified', 'SprayingOperator', 'SafetyHandling'],
    hourlyRate: 18.5,
    isAvailable: true,
    activeTasksCount: 1,
    contactNumber: '+94 77 123 4567',
  },
  {
    id: 'w-102',
    name: 'Amara Weerasinghe',
    skills: ['FungicideSpecialist', 'Pruning', 'CropScouting'],
    hourlyRate: 20.0,
    isAvailable: true,
    activeTasksCount: 0,
    contactNumber: '+94 71 987 6543',
  },
  {
    id: 'w-103',
    name: 'Sunil Perera',
    skills: ['IrrigationManagement', 'SoilTesting', 'FertilizerApplication'],
    hourlyRate: 17.0,
    isAvailable: true,
    activeTasksCount: 2,
    contactNumber: '+94 75 456 7890',
  },
  {
    id: 'w-104',
    name: 'Nimali Jayawardena',
    skills: ['Harvesting', 'QualityGrading', 'GreenhouseOperations'],
    hourlyRate: 16.5,
    isAvailable: false,
    activeTasksCount: 3,
    contactNumber: '+94 72 333 4455',
  },
];

export const INITIAL_MOCK_TASKS = [
  {
    id: 'tsk-001',
    title: 'Biological Bt Spray Application',
    description: 'Apply Bacillus thuringiensis spray to suppress tomato fruitworm larvae before fruit penetration.',
    taskType: 'PesticideApplication',
    priority: 'Critical',
    status: 'Pending',
    fieldId: 'field-north-plot-99',
    assignedWorkerId: null,
    assignedWorkerName: null,
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    cropVariety: 'Tomato',
    estimatedHours: 3.5,
    sourceCropAnalysisId: 'ana-001',
  },
  {
    id: 'tsk-002',
    title: 'Copper Hydroxide Fungicide Treatment',
    description: 'Apply copper hydroxide spray at 2.0 kg/ha to arrest early blight spreading on foliage.',
    taskType: 'PestInspection',
    priority: 'High',
    status: 'Assigned',
    fieldId: 'field-east-fungus-02',
    assignedWorkerId: 'w-102',
    assignedWorkerName: 'Amara Weerasinghe',
    dueDate: new Date(Date.now() + 172800000).toISOString(),
    cropVariety: 'Tomato',
    estimatedHours: 4.0,
    sourceCropAnalysisId: 'ana-002',
  },
  {
    id: 'tsk-003',
    title: 'Plot Soil Nitrate & Iron Chlorosis Check',
    description: 'Conduct leaf tissue sampling and verify nitrogen drip irrigation levels.',
    taskType: 'CropMonitoring',
    priority: 'Medium',
    status: 'InProgress',
    fieldId: 'field-south-veg-12',
    assignedWorkerId: 'w-101',
    assignedWorkerName: 'Kasun Bandara',
    dueDate: new Date(Date.now() + 259200000).toISOString(),
    cropVariety: 'Tomato',
    estimatedHours: 2.0,
    sourceCropAnalysisId: null,
  },
  {
    id: 'tsk-004',
    title: 'Section B Drip Line Descaling',
    description: 'Flush drip emitters and verify pressure balance across northern tomato plots.',
    taskType: 'Irrigation',
    priority: 'Low',
    status: 'PendingVerification',
    fieldId: 'field-west-irrig-04',
    assignedWorkerId: 'w-103',
    assignedWorkerName: 'Sunil Perera',
    dueDate: new Date(Date.now() - 3600000).toISOString(),
    cropVariety: 'Tomato',
    estimatedHours: 2.5,
    sourceCropAnalysisId: null,
    evidence: {
      photoUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985b?auto=format&fit=crop&w=600&q=80',
      submittedAt: new Date(Date.now() - 7200000).toISOString(),
      notes: 'Descaling solution flushed through lines 1-6. Emitter flow rate restored to 2.1 L/hr. Photos attached.',
    },
  },
  {
    id: 'tsk-005',
    title: 'Routine Vegetative Vigor Scouting',
    description: 'Scout northern quadrant for foliage pests and leaf discoloration.',
    taskType: 'CropMonitoring',
    priority: 'Low',
    status: 'Completed',
    fieldId: 'field-north-plot-1',
    assignedWorkerId: 'w-101',
    assignedWorkerName: 'Kasun Bandara',
    dueDate: new Date(Date.now() - 86400000).toISOString(),
    cropVariety: 'Tomato',
    estimatedHours: 1.5,
    sourceCropAnalysisId: null,
  },
];

export const INITIAL_MOCK_APPROVALS = [
  {
    id: 'ana-001',
    threadId: 'thread-crit-tomato-99',
    fieldId: 'field-north-plot-99',
    cropVariety: 'Tomato',
    growthStage: 'Fruiting',
    observation: 'Caterpillars and fruitworms chewing extensive entry holes into developing green tomato fruits.',
    primaryIndicator: 'Tomato Fruitworm Infestation (Helicoverpa zea)',
    category: 'Pest',
    riskLevel: 'Critical',
    suggestedTaskType: 'PesticideApplication',
    priority: 'Critical',
    confidenceScore: 0.94,
    recommendedProtocol: 'Deploy biological Bt spray and pheromone traps. Immediate sanitation required.',
    sourceHandbook: '[Tomato-Handbook]',
    status: 'AwaitingApproval',
    detectedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'ana-002',
    threadId: 'thread-high-blight-05',
    fieldId: 'field-east-fungus-02',
    cropVariety: 'Tomato',
    growthStage: 'Flowering',
    observation: 'Dark brown concentric target spots expanding on lower foliage with yellow chlorotic halos.',
    primaryIndicator: 'Early Blight (Alternaria solani)',
    category: 'Disease',
    riskLevel: 'High',
    suggestedTaskType: 'PestInspection',
    priority: 'High',
    confidenceScore: 0.91,
    recommendedProtocol: 'Apply copper hydroxide fungicide spray at 2.0 kg/ha. Prune lower diseased foliage.',
    sourceHandbook: '[Tomato-Handbook]',
    status: 'AwaitingApproval',
    detectedAt: new Date(Date.now() - 7200000).toISOString(),
  },
];
