import 'package:flutter_test/flutter_test.dart';
import 'package:agriops_mobile/models/farm.dart';

void main() {
  group('Farm Model Unit Tests (Component 1)', () {
    test('Farm.fromJson correctly deserializes JSON payload', () {
      final json = {
        'id': 'farm-101',
        'name': 'Green Hills Tea & Spices',
        'location': 'Kandy, Central Province',
        'totalArea': 45.5,
        'ownerId': 'user-owner-1',
      };

      final farm = Farm.fromJson(json);

      expect(farm.id, 'farm-101');
      expect(farm.name, 'Green Hills Tea & Spices');
      expect(farm.location, 'Kandy, Central Province');
      expect(farm.totalArea, 45.5);
      expect(farm.ownerId, 'user-owner-1');
    });

    test('Farm.toCreateJson creates valid POST body', () {
      final farm = Farm(
        id: 'temp-id',
        name: 'Hilltop Coconut Grove',
        location: 'Kurunegala',
        totalArea: 12.0,
        ownerId: 'owner-99',
      );

      final payload = farm.toCreateJson();

      expect(payload['name'], 'Hilltop Coconut Grove');
      expect(payload['location'], 'Kurunegala');
      expect(payload['totalArea'], 12.0);
      expect(payload['ownerId'], 'owner-99');
      expect(payload.containsKey('id'), false); // ID is generated by backend
    });
  });
}
